<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Laraeast\LaravelSettings\Facades\Settings;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Settings::locale('ar')->set('name', 'عطوراتي');
        Settings::locale('en')->set('name', 'Otoraty');
        Settings::set('slider')
            ->addMedia(resource_path('otoraty-design/img/slide-1.png'))
            ->preservingOriginal()
            ->toMediaCollection('slider');

        Settings::locale('ar')->set('block1', '<h4>ارسل هديتك والباقي علينا</h4>
                        <p>مع خيارات الهدايا اللامتناهية، قد تسأل نفسك لماذا يتوجب عليك شراء العطر؟ حسنا، العطر ليس مجرد
                            منتج متعدد الاستخدامات -
                            مثل انتعاش الملابس أو اضفاء جو رائع داخل المنزل. انها هدية تخاطب الإحساس
                        </p>
                        <p>اهداء العطر لشخص ما هو دليل على أنكم قد فكرتم مليا في شخصية المتلقي و في أذواقه. كما انه منتج
                            سوف
                            يرتديه بشكل يومي – ما
                            سيجعله يفكر فيكم باستمرار. لهذا فان إهداء شخص ما قارورة عطر هو دليل على المودة.
                        </p>
                        <p>أخيرا و ليس آخرا، تعتبر العطور من الهدايا الخاصة لأنها منتجات لا تشترى في الكثير من الأحيان.
                            انها
                            إشارة على قيمة المتلقي
                            لديكم.
                        </p>');
        Settings::locale('en')->set('block1', '<h4> Send your gift and the rest to us </h4>
                        <p> With the endless gifting options, you might ask yourself why should you buy perfume? Well, just not perfume
                            Versatile product -
                            Like refreshing clothes or adding a wonderful atmosphere inside the house. It\'s a gift that speaks to emotion
    </p>
                        <p> Giving a perfume to someone is evidence that you have thought carefully about the recipient\'s personality and tastes. He is also a producer
                            Will
                            Wears it on a daily basis - what
                            It will make him think of you constantly. This is why gifting someone a bottle of perfume is a sign of affection.
                        </p>
                        <p> Last, but not least, perfumes are a special gift because they are products that are not often bought.
                            It
                            Signal on the value of the receiver
                            You have.
                        </p>');
        Settings::set('block1-img')
            ->addMedia(resource_path('otoraty-design/img/notice.png'))
            ->preservingOriginal()
            ->toMediaCollection('block1-img');

        Settings::locale('ar')->set('block2', '<h4> اترك علامة </h4>
                        <p> هذا النص هو مثال لن يستبدل في نفس المساحة ، لقد تم توليد هذا النص من مولد النص
                            العربى ،
                            حيث يمكنك أن تولد مثل هذا
                            إضافة إلى زيادة عدد الحروف التي يولدها التطبيق. <p>');
        Settings::locale('en')->set('block2', '<h4> Leave tag </h4>
                         <p> This text is an example that will not be replaced in the same space. This text was generated from the text generator
                             Arabi ,
                             Where you can generate it like this
                             In addition to increasing the number of characters generated by the application. <p>');
        Settings::set('block2-img')
            ->addMedia(resource_path('otoraty-design/img/notice.png'))
            ->preservingOriginal()
            ->toMediaCollection('block2-img');

        Settings::set('instagram', 'https://instagram.com');
        Settings::set('snapchat', 'https://snapchat.com');
        Settings::set('twitter', 'https://twitter.com');
        Settings::set('apple', '#');
        Settings::set('android', '#');
        Settings::set('phone', '123456');
        Settings::set('email', 'support@demo.com');
        Settings::locale('ar')->set('copyright', 'عطوراتى جميع الحقوق محفوظة');
        Settings::locale('en')->set('copyright', 'All right received for Otoraty.');
    }
}
